//----------------------------------------------------------------------------//
// This unit was automatically generated by the RemObjects SDK after reading  //
// the RODL file associated with this project .                               //
//                                                                            //
// Do not modify this unit manually, or your changes will be lost when this   //
// unit is regenerated the next time you compile the project.                 //
//----------------------------------------------------------------------------//


/* This codegen depends on RemObjectsSDK.js
* Usage:
* var Channel = new RemObjects.SDK.HTTPClientChannel("http://localhost:8099/JSON");
* var Message = new RemObjects.SDK.JSONMessage();
* var Service = new NewService(Channel, Message);
* Service.Sum(1, 2,
*             function(result) {
*                 alert(result);
*             },
*             function(msg) {alert(msg.getErrorMessage())}
* );
*
*/

__namespace = this;
if ("" != "") {
	var parts = "".split(".");
	var current = this;
    for (var i = 0; i < parts.length; i++) {
		current[parts[i]] = current[parts[i]] || {};
		current = current[parts[i]];
    };
	__namespace = current;
};

// Enum: TSex
__namespace.TSex = function TSex() {
  this.value = null;
};
__namespace.TSex.prototype = new RemObjects.SDK.ROEnumType();
__namespace.TSex.prototype.enumValues = [
    "sxMale",
    "sxFemale"
	];
__namespace.TSex.prototype.constructor = __namespace.TSex;
RemObjects.SDK.RTTI["TSex"] = __namespace.TSex;


// Struct: TPersoon
__namespace.TPersoon = function TPersoon() {
    this.Aanhef = {dataType : "AnsiString", value : null};
    this.AanhefOms = {dataType : "AnsiString", value : null};
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.BedragBetaald = {dataType : "Currency", value : null};
    this.BedragOpenstaand = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.BetaalWijze = {dataType : "AnsiString", value : null};
    this.DatumEind = {dataType : "DateTime", value : null};
    this.DatumGeb = {dataType : "DateTime", value : null};
    this.DatumInschr = {dataType : "DateTime", value : null};
    this.DatumInvoer = {dataType : "DateTime", value : null};
    this.DatumMutatie = {dataType : "DateTime", value : null};
    this.DatumOndertekening = {dataType : "DateTime", value : null};
    this.Email = {dataType : "AnsiString", value : null};
    this.Email2 = {dataType : "AnsiString", value : null};
    this.Geslacht = {dataType : "AnsiString", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.Groepen = {dataType : "AnsiString", value : null};
    this.GroepOms = {dataType : "AnsiString", value : null};
    this.HfdBew = {dataType : "AnsiString", value : null};
    this.Hoofdbewoner = {dataType : "Boolean", value : null};
    this.HuisNr = {dataType : "AnsiString", value : null};
    this.HuisNrAanv = {dataType : "AnsiString", value : null};
    this.IncassoUitgevoerd = {dataType : "Boolean", value : null};
    this.KodeExtern = {dataType : "AnsiString", value : null};
    this.Land = {dataType : "AnsiString", value : null};
    this.Leeftijd = {dataType : "Integer", value : null};
    this.LidNr = {dataType : "Integer", value : null};
    this.MachtigingsID = {dataType : "AnsiString", value : null};
    this.MailingList = {dataType : "Boolean", value : null};
    this.Medebewoners = {dataType : "Boolean", value : null};
    this.Naam = {dataType : "AnsiString", value : null};
    this.Naam_2 = {dataType : "AnsiString", value : null};
    this.Opmerking = {dataType : "WideString", value : null};
    this.Plaats = {dataType : "AnsiString", value : null};
    this.Postcode = {dataType : "AnsiString", value : null};
    this.RedenEind = {dataType : "AnsiString", value : null};
    this.RedenInschrijving = {dataType : "AnsiString", value : null};
    this.Regio = {dataType : "AnsiString", value : null};
    this.RegioOms = {dataType : "AnsiString", value : null};
    this.SofiNr = {dataType : "Double", value : null};
    this.SoortLid = {dataType : "AnsiString", value : null};
    this.SoortLidOms = {dataType : "AnsiString", value : null};
    this.Straat = {dataType : "AnsiString", value : null};
    this.StraatAanv = {dataType : "AnsiString", value : null};
    this.TelNr = {dataType : "AnsiString", value : null};
    this.TelNrMobiel = {dataType : "AnsiString", value : null};
    this.TelNrWerk = {dataType : "AnsiString", value : null};
    this.Titel = {dataType : "AnsiString", value : null};
    this.Tussenvoegsel = {dataType : "AnsiString", value : null};
    this.Vlag1 = {dataType : "Boolean", value : null};
    this.Vlag10 = {dataType : "Boolean", value : null};
    this.Vlag11 = {dataType : "Boolean", value : null};
    this.Vlag12 = {dataType : "Boolean", value : null};
    this.Vlag13 = {dataType : "Boolean", value : null};
    this.Vlag14 = {dataType : "Boolean", value : null};
    this.Vlag15 = {dataType : "Boolean", value : null};
    this.Vlag16 = {dataType : "Boolean", value : null};
    this.Vlag2 = {dataType : "Boolean", value : null};
    this.Vlag3 = {dataType : "Boolean", value : null};
    this.Vlag4 = {dataType : "Boolean", value : null};
    this.Vlag5 = {dataType : "Boolean", value : null};
    this.Vlag6 = {dataType : "Boolean", value : null};
    this.Vlag7 = {dataType : "Boolean", value : null};
    this.Vlag8 = {dataType : "Boolean", value : null};
    this.Vlag9 = {dataType : "Boolean", value : null};
    this.Voorletters = {dataType : "AnsiString", value : null};
    this.Voornaam = {dataType : "AnsiString", value : null};
};
__namespace.TPersoon.prototype = new RemObjects.SDK.ROStructType();
__namespace.TPersoon.prototype.constructor = __namespace.TPersoon;
RemObjects.SDK.RTTI["TPersoon"] = __namespace.TPersoon;

// Struct: TPersoonDetail
__namespace.TPersoonDetail = function TPersoonDetail() {
    this.Aanhef = {dataType : "AnsiString", value : null};
    this.AanhefOms = {dataType : "AnsiString", value : null};
    this.AanhefTitel = {dataType : "AnsiString", value : null};
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.Achtervoegsel = {dataType : "AnsiString", value : null};
    this.Adres3 = {dataType : "Boolean", value : null};
    this.Adres3Factuur = {dataType : "Boolean", value : null};
    this.Adres3Woon = {dataType : "Boolean", value : null};
    this.AdresFactuur = {dataType : "Boolean", value : null};
    this.AdresPost = {dataType : "Boolean", value : null};
    this.AdresWoon = {dataType : "Boolean", value : null};
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.Bedrag1 = {dataType : "Currency", value : null};
    this.Bedrag2 = {dataType : "Currency", value : null};
    this.Bedrag3 = {dataType : "Currency", value : null};
    this.Bedrag4 = {dataType : "Currency", value : null};
    this.BedragAccept = {dataType : "Currency", value : null};
    this.BedragBetaald = {dataType : "Currency", value : null};
    this.BedragOpenstaand = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.BetaalPeriode = {dataType : "AnsiString", value : null};
    this.BetaalWijze = {dataType : "AnsiString", value : null};
    this.BezorgNr = {dataType : "Integer", value : null};
    this.Bondslid = {dataType : "Boolean", value : null};
    this.BurgStaat = {dataType : "AnsiString", value : null};
    this.Categorie = {dataType : "AnsiString", value : null};
    this.Code1 = {dataType : "AnsiString", value : null};
    this.Code2 = {dataType : "AnsiString", value : null};
    this.Code3 = {dataType : "AnsiString", value : null};
    this.Code4 = {dataType : "AnsiString", value : null};
    this.Contributie = {dataType : "AnsiString", value : null};
    this.Cursussen = {dataType : "WideString", value : null};
    this.Dag = {dataType : "Integer", value : null};
    this.DatumAanmeldBond = {dataType : "DateTime", value : null};
    this.DatumAfmeldBond = {dataType : "DateTime", value : null};
    this.DatumBetaald = {dataType : "DateTime", value : null};
    this.DatumEind = {dataType : "DateTime", value : null};
    this.DatumEind3 = {dataType : "DateTime", value : null};
    this.DatumEindPost = {dataType : "DateTime", value : null};
    this.DatumGeb = {dataType : "DateTime", value : null};
    this.DatumGeb_2 = {dataType : "DateTime", value : null};
    this.DatumIngang3 = {dataType : "DateTime", value : null};
    this.DatumIngangPost = {dataType : "DateTime", value : null};
    this.DatumInschr = {dataType : "DateTime", value : null};
    this.DatumInvoer = {dataType : "DateTime", value : null};
    this.DatumMutatie = {dataType : "DateTime", value : null};
    this.DatumMutatieBond = {dataType : "DateTime", value : null};
    this.DatumMutatieBondVerwerkt = {dataType : "DateTime", value : null};
    this.DatumOndertekening = {dataType : "DateTime", value : null};
    this.Decimaal1 = {dataType : "Double", value : null};
    this.Decimaal2 = {dataType : "Double", value : null};
    this.Decimaal3 = {dataType : "Double", value : null};
    this.Decimaal4 = {dataType : "Double", value : null};
    this.Dispensatie = {dataType : "Boolean", value : null};
    this.Email = {dataType : "AnsiString", value : null};
    this.Email2 = {dataType : "AnsiString", value : null};
    this.Fax = {dataType : "AnsiString", value : null};
    this.FotoNr = {dataType : "Double", value : null};
    this.Geslacht = {dataType : "AnsiString", value : null};
    this.Geslacht_2 = {dataType : "AnsiString", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.Groepen = {dataType : "AnsiString", value : null};
    this.GroepOms = {dataType : "AnsiString", value : null};
    this.HfdBew = {dataType : "AnsiString", value : null};
    this.Hoofdbewoner = {dataType : "Boolean", value : null};
    this.HuisNr = {dataType : "AnsiString", value : null};
    this.HuisNr3 = {dataType : "AnsiString", value : null};
    this.HuisNrAanv = {dataType : "AnsiString", value : null};
    this.HuisNrAanv3 = {dataType : "AnsiString", value : null};
    this.HuisNrAanvPost = {dataType : "AnsiString", value : null};
    this.HuisNrPost = {dataType : "AnsiString", value : null};
    this.HuisNrSort = {dataType : "AnsiString", value : null};
    this.IDNr = {dataType : "AnsiString", value : null};
    this.IncassoUitgevoerd = {dataType : "Boolean", value : null};
    this.Kenmerk1 = {dataType : "AnsiString", value : null};
    this.Kenmerk2 = {dataType : "AnsiString", value : null};
    this.Kenmerk3 = {dataType : "AnsiString", value : null};
    this.Kenmerk4 = {dataType : "AnsiString", value : null};
    this.KodeExtern = {dataType : "AnsiString", value : null};
    this.Land = {dataType : "AnsiString", value : null};
    this.Land3 = {dataType : "AnsiString", value : null};
    this.LandGeb = {dataType : "AnsiString", value : null};
    this.LandPost = {dataType : "AnsiString", value : null};
    this.LandVol = {dataType : "AnsiString", value : null};
    this.Leeftijd = {dataType : "Integer", value : null};
    this.LidNr = {dataType : "Integer", value : null};
    this.LidNrChar = {dataType : "AnsiString", value : null};
    this.LidNrPost = {dataType : "Integer", value : null};
    this.LidNr_2 = {dataType : "Integer", value : null};
    this.Maand = {dataType : "AnsiString", value : null};
    this.MachtigingsID = {dataType : "AnsiString", value : null};
    this.MailingList = {dataType : "Boolean", value : null};
    this.Medebewoners = {dataType : "Boolean", value : null};
    this.Meisjesnaam = {dataType : "Boolean", value : null};
    this.Memo = {dataType : "WideString", value : null};
    this.Naam = {dataType : "AnsiString", value : null};
    this.Naam3 = {dataType : "AnsiString", value : null};
    this.NaamAanv3 = {dataType : "AnsiString", value : null};
    this.NaamAanvPost = {dataType : "AnsiString", value : null};
    this.NaamPost = {dataType : "AnsiString", value : null};
    this.NaamVol = {dataType : "AnsiString", value : null};
    this.Naam_2 = {dataType : "AnsiString", value : null};
    this.Nationaliteit = {dataType : "AnsiString", value : null};
    this.Nummer1 = {dataType : "Double", value : null};
    this.Nummer2 = {dataType : "Double", value : null};
    this.Nummer3 = {dataType : "Double", value : null};
    this.Nummer4 = {dataType : "Double", value : null};
    this.Opmerking = {dataType : "WideString", value : null};
    this.Plaats = {dataType : "AnsiString", value : null};
    this.Plaats3 = {dataType : "AnsiString", value : null};
    this.PlaatsGeb = {dataType : "AnsiString", value : null};
    this.PlaatsPost = {dataType : "AnsiString", value : null};
    this.PlaatsVol = {dataType : "AnsiString", value : null};
    this.Postcode = {dataType : "AnsiString", value : null};
    this.Postcode3 = {dataType : "AnsiString", value : null};
    this.PostcodeGecontroleerd = {dataType : "Boolean", value : null};
    this.PostcodePost = {dataType : "AnsiString", value : null};
    this.RedenEind = {dataType : "AnsiString", value : null};
    this.RedenInschrijving = {dataType : "AnsiString", value : null};
    this.Regio = {dataType : "AnsiString", value : null};
    this.RegioOms = {dataType : "AnsiString", value : null};
    this.Roepnaam = {dataType : "AnsiString", value : null};
    this.Sectie = {dataType : "Integer", value : null};
    this.SofiNr = {dataType : "Double", value : null};
    this.SoortCorr = {dataType : "AnsiString", value : null};
    this.SoortID = {dataType : "AnsiString", value : null};
    this.SoortLid = {dataType : "AnsiString", value : null};
    this.SoortLidOms = {dataType : "AnsiString", value : null};
    this.SpeelSterkteDubbel = {dataType : "Integer", value : null};
    this.SpeelSterkteEnkel = {dataType : "Integer", value : null};
    this.Straat = {dataType : "AnsiString", value : null};
    this.Straat3 = {dataType : "AnsiString", value : null};
    this.StraatAanv = {dataType : "AnsiString", value : null};
    this.StraatAanv3 = {dataType : "AnsiString", value : null};
    this.StraatAanvPost = {dataType : "AnsiString", value : null};
    this.StraatPost = {dataType : "AnsiString", value : null};
    this.StraatVol = {dataType : "AnsiString", value : null};
    this.Team = {dataType : "AnsiString", value : null};
    this.TelGeheim = {dataType : "Boolean", value : null};
    this.TelNr = {dataType : "AnsiString", value : null};
    this.TelNrMobiel = {dataType : "AnsiString", value : null};
    this.TelNrWerk = {dataType : "AnsiString", value : null};
    this.Titel = {dataType : "AnsiString", value : null};
    this.TitelOms = {dataType : "AnsiString", value : null};
    this.Tnv = {dataType : "AnsiString", value : null};
    this.TnvAdres = {dataType : "AnsiString", value : null};
    this.TnvLand = {dataType : "AnsiString", value : null};
    this.TnvPlaats = {dataType : "AnsiString", value : null};
    this.TnvPostcode = {dataType : "AnsiString", value : null};
    this.Tstamp = {dataType : "DateTime", value : null};
    this.Tussenvoegsel = {dataType : "AnsiString", value : null};
    this.URL = {dataType : "AnsiString", value : null};
    this.Verjaardag = {dataType : "AnsiString", value : null};
    this.Vlag1 = {dataType : "Boolean", value : null};
    this.Vlag10 = {dataType : "Boolean", value : null};
    this.Vlag11 = {dataType : "Boolean", value : null};
    this.Vlag12 = {dataType : "Boolean", value : null};
    this.Vlag13 = {dataType : "Boolean", value : null};
    this.Vlag14 = {dataType : "Boolean", value : null};
    this.Vlag15 = {dataType : "Boolean", value : null};
    this.Vlag16 = {dataType : "Boolean", value : null};
    this.Vlag2 = {dataType : "Boolean", value : null};
    this.Vlag3 = {dataType : "Boolean", value : null};
    this.Vlag4 = {dataType : "Boolean", value : null};
    this.Vlag5 = {dataType : "Boolean", value : null};
    this.Vlag6 = {dataType : "Boolean", value : null};
    this.Vlag7 = {dataType : "Boolean", value : null};
    this.Vlag8 = {dataType : "Boolean", value : null};
    this.Vlag9 = {dataType : "Boolean", value : null};
    this.Voldaan = {dataType : "Boolean", value : null};
    this.Voorletters = {dataType : "AnsiString", value : null};
    this.Voornaam = {dataType : "AnsiString", value : null};
    this.Wijk = {dataType : "Integer", value : null};
    this.Zoeknaam = {dataType : "AnsiString", value : null};
};
__namespace.TPersoonDetail.prototype = new RemObjects.SDK.ROStructType();
__namespace.TPersoonDetail.prototype.constructor = __namespace.TPersoonDetail;
RemObjects.SDK.RTTI["TPersoonDetail"] = __namespace.TPersoonDetail;

// Struct: TUser
__namespace.TUser = function TUser() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Email = {dataType : "AnsiString", value : null};
    this.Passwrd = {dataType : "AnsiString", value : null};
    this.Token = {dataType : "AnsiString", value : null};
    this.Username = {dataType : "AnsiString", value : null};
    this.Name = {dataType : "AnsiString", value : null};
};
__namespace.TUser.prototype = new RemObjects.SDK.ROStructType();
__namespace.TUser.prototype.constructor = __namespace.TUser;
RemObjects.SDK.RTTI["TUser"] = __namespace.TUser;

// Struct: TSoortLid
__namespace.TSoortLid = function TSoortLid() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.SoortLid = {dataType : "AnsiString", value : null};
};
__namespace.TSoortLid.prototype = new RemObjects.SDK.ROStructType();
__namespace.TSoortLid.prototype.constructor = __namespace.TSoortLid;
RemObjects.SDK.RTTI["TSoortLid"] = __namespace.TSoortLid;

// Struct: TMutReden
__namespace.TMutReden = function TMutReden() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.MutReden = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.SoortMut = {dataType : "AnsiString", value : null};
    this.StopFactureren = {dataType : "Boolean", value : null};
};
__namespace.TMutReden.prototype = new RemObjects.SDK.ROStructType();
__namespace.TMutReden.prototype.constructor = __namespace.TMutReden;
RemObjects.SDK.RTTI["TMutReden"] = __namespace.TMutReden;

// Struct: TFunctie
__namespace.TFunctie = function TFunctie() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Functie = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
};
__namespace.TFunctie.prototype = new RemObjects.SDK.ROStructType();
__namespace.TFunctie.prototype.constructor = __namespace.TFunctie;
RemObjects.SDK.RTTI["TFunctie"] = __namespace.TFunctie;

// Struct: TSoortBetaling
__namespace.TSoortBetaling = function TSoortBetaling() {
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.Actief = {dataType : "Boolean", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.BTWCode = {dataType : "AnsiString", value : null};
    this.DefaultTermijn = {dataType : "AnsiString", value : null};
    this.Eenmalig = {dataType : "Boolean", value : null};
    this.IndProlongeren = {dataType : "Boolean", value : null};
    this.Negatief = {dataType : "Boolean", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.SoortBetaling = {dataType : "AnsiString", value : null};
    this.Volgorde = {dataType : "Integer", value : null};
};
__namespace.TSoortBetaling.prototype = new RemObjects.SDK.ROStructType();
__namespace.TSoortBetaling.prototype.constructor = __namespace.TSoortBetaling;
RemObjects.SDK.RTTI["TSoortBetaling"] = __namespace.TSoortBetaling;

// Struct: TAanhef
__namespace.TAanhef = function TAanhef() {
    this.Aanhef = {dataType : "AnsiString", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Geslacht = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
};
__namespace.TAanhef.prototype = new RemObjects.SDK.ROStructType();
__namespace.TAanhef.prototype.constructor = __namespace.TAanhef;
RemObjects.SDK.RTTI["TAanhef"] = __namespace.TAanhef;

// Struct: TTitel
__namespace.TTitel = function TTitel() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.Titel = {dataType : "AnsiString", value : null};
};
__namespace.TTitel.prototype = new RemObjects.SDK.ROStructType();
__namespace.TTitel.prototype.constructor = __namespace.TTitel;
RemObjects.SDK.RTTI["TTitel"] = __namespace.TTitel;

// Struct: TCategorie
__namespace.TCategorie = function TCategorie() {
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Betaalwijze = {dataType : "AnsiString", value : null};
    this.Categorie = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.RekeningNr = {dataType : "AnsiString", value : null};
};
__namespace.TCategorie.prototype = new RemObjects.SDK.ROStructType();
__namespace.TCategorie.prototype.constructor = __namespace.TCategorie;
RemObjects.SDK.RTTI["TCategorie"] = __namespace.TCategorie;

// Struct: TKenmerk
__namespace.TKenmerk = function TKenmerk() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.IndNieuw = {dataType : "Boolean", value : null};
    this.Kenmerk = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
};
__namespace.TKenmerk.prototype = new RemObjects.SDK.ROStructType();
__namespace.TKenmerk.prototype.constructor = __namespace.TKenmerk;
RemObjects.SDK.RTTI["TKenmerk"] = __namespace.TKenmerk;

// Struct: TKenmKode
__namespace.TKenmKode = function TKenmKode() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Extra1 = {dataType : "AnsiString", value : null};
    this.Extra2 = {dataType : "AnsiString", value : null};
    this.Extra3 = {dataType : "AnsiString", value : null};
    this.Kenmerk = {dataType : "AnsiString", value : null};
    this.Kode = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
};
__namespace.TKenmKode.prototype = new RemObjects.SDK.ROStructType();
__namespace.TKenmKode.prototype.constructor = __namespace.TKenmKode;
RemObjects.SDK.RTTI["TKenmKode"] = __namespace.TKenmKode;

// Struct: TGroep
__namespace.TGroep = function TGroep() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.Periode = {dataType : "Integer", value : null};
};
__namespace.TGroep.prototype = new RemObjects.SDK.ROStructType();
__namespace.TGroep.prototype.constructor = __namespace.TGroep;
RemObjects.SDK.RTTI["TGroep"] = __namespace.TGroep;

// Struct: TGrpBet
__namespace.TGrpBet = function TGrpBet() {
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.Bedrag1 = {dataType : "Currency", value : null};
    this.Bedrag10 = {dataType : "Currency", value : null};
    this.Bedrag11 = {dataType : "Currency", value : null};
    this.Bedrag12 = {dataType : "Currency", value : null};
    this.Bedrag2 = {dataType : "Currency", value : null};
    this.Bedrag3 = {dataType : "Currency", value : null};
    this.Bedrag4 = {dataType : "Currency", value : null};
    this.Bedrag5 = {dataType : "Currency", value : null};
    this.Bedrag6 = {dataType : "Currency", value : null};
    this.Bedrag7 = {dataType : "Currency", value : null};
    this.Bedrag8 = {dataType : "Currency", value : null};
    this.Bedrag9 = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.Periode = {dataType : "Integer", value : null};
    this.SoortBetaling = {dataType : "AnsiString", value : null};
};
__namespace.TGrpBet.prototype = new RemObjects.SDK.ROStructType();
__namespace.TGrpBet.prototype.constructor = __namespace.TGrpBet;
RemObjects.SDK.RTTI["TGrpBet"] = __namespace.TGrpBet;

// Struct: TPersPeri
__namespace.TPersPeri = function TPersPeri() {
    this.Aantal = {dataType : "Integer", value : null};
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.BedragBetaald = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.BetaalWijze = {dataType : "AnsiString", value : null};
    this.DatumBetaald = {dataType : "DateTime", value : null};
    this.DatumEind = {dataType : "DateTime", value : null};
    this.DatumFactuur = {dataType : "DateTime", value : null};
    this.DatumIngang = {dataType : "DateTime", value : null};
    this.DatumVerstuurd = {dataType : "DateTime", value : null};
    this.Dispensatie = {dataType : "Boolean", value : null};
    this.Factuurnr = {dataType : "AnsiString", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.LidNr = {dataType : "Integer", value : null};
    this.Opmerking = {dataType : "WideString", value : null};
    this.Periode = {dataType : "Integer", value : null};
    this.TermijnNr = {dataType : "Integer", value : null};
};
__namespace.TPersPeri.prototype = new RemObjects.SDK.ROStructType();
__namespace.TPersPeri.prototype.constructor = __namespace.TPersPeri;
RemObjects.SDK.RTTI["TPersPeri"] = __namespace.TPersPeri;

// Struct: TPersBet
__namespace.TPersBet = function TPersBet() {
    this.Aantal = {dataType : "Integer", value : null};
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.AantalTermijnenVrij = {dataType : "Integer", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.BedragBetaald = {dataType : "Currency", value : null};
    this.BedragKorting = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.DatumIngang = {dataType : "DateTime", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.LaatsteTermijn = {dataType : "Integer", value : null};
    this.LidNr = {dataType : "Integer", value : null};
    this.MutatieDatum = {dataType : "DateTime", value : null};
    this.Periode = {dataType : "Integer", value : null};
    this.SoortBetaling = {dataType : "AnsiString", value : null};
    this.TermijnNr = {dataType : "Integer", value : null};
};
__namespace.TPersBet.prototype = new RemObjects.SDK.ROStructType();
__namespace.TPersBet.prototype.constructor = __namespace.TPersBet;
RemObjects.SDK.RTTI["TPersBet"] = __namespace.TPersBet;

// Struct: TBetaling
__namespace.TBetaling = function TBetaling() {
    this.AfschriftNr = {dataType : "Integer", value : null};
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.BankRekNrBedr = {dataType : "AnsiString", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.BedragAfgeletterd = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Betaalwijze = {dataType : "AnsiString", value : null};
    this.BetalingNr = {dataType : "Integer", value : null};
    this.BetalingsKenmerk = {dataType : "AnsiString", value : null};
    this.Categorie = {dataType : "AnsiString", value : null};
    this.Datum = {dataType : "DateTime", value : null};
    this.DatumGeboekt = {dataType : "DateTime", value : null};
    this.Groep = {dataType : "AnsiString", value : null};
    this.Historie = {dataType : "Boolean", value : null};
    this.Jaar = {dataType : "Integer", value : null};
    this.LidNr = {dataType : "Integer", value : null};
    this.MutReden = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.Opmerking = {dataType : "WideString", value : null};
    this.Periode = {dataType : "Integer", value : null};
    this.RegelNr = {dataType : "Integer", value : null};
    this.SoortBetaling = {dataType : "AnsiString", value : null};
};
__namespace.TBetaling.prototype = new RemObjects.SDK.ROStructType();
__namespace.TBetaling.prototype.constructor = __namespace.TBetaling;
RemObjects.SDK.RTTI["TBetaling"] = __namespace.TBetaling;

// Struct: TRegio
__namespace.TRegio = function TRegio() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
    this.Regio = {dataType : "AnsiString", value : null};
};
__namespace.TRegio.prototype = new RemObjects.SDK.ROStructType();
__namespace.TRegio.prototype.constructor = __namespace.TRegio;
RemObjects.SDK.RTTI["TRegio"] = __namespace.TRegio;

// Struct: TGrp
__namespace.TGrp = function TGrp() {
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Grp = {dataType : "AnsiString", value : null};
    this.Omschrijving = {dataType : "AnsiString", value : null};
};
__namespace.TGrp.prototype = new RemObjects.SDK.ROStructType();
__namespace.TGrp.prototype.constructor = __namespace.TGrp;
RemObjects.SDK.RTTI["TGrp"] = __namespace.TGrp;

// Struct: TBedrijf
__namespace.TBedrijf = function TBedrijf() {
    this.AantalTermijnen = {dataType : "Integer", value : null};
    this.Acc_Bold = {dataType : "Boolean", value : null};
    this.Acc_Doc = {dataType : "AnsiString", value : null};
    this.Acc_Font = {dataType : "AnsiString", value : null};
    this.Acc_Italic = {dataType : "Boolean", value : null};
    this.Acc_Left = {dataType : "Integer", value : null};
    this.Acc_Soort = {dataType : "AnsiString", value : null};
    this.Acc_Tekst1 = {dataType : "WideString", value : null};
    this.Acc_Tekst2 = {dataType : "WideString", value : null};
    this.Acc_Tekst3 = {dataType : "WideString", value : null};
    this.Acc_Top = {dataType : "Integer", value : null};
    this.Actuaris = {dataType : "Integer", value : null};
    this.AdmNr = {dataType : "AnsiString", value : null};
    this.AdresOpAccGiro = {dataType : "Boolean", value : null};
    this.Afdeling = {dataType : "AnsiString", value : null};
    this.BankRekNr = {dataType : "AnsiString", value : null};
    this.BankRekProef = {dataType : "Integer", value : null};
    this.Bedrag = {dataType : "Currency", value : null};
    this.Bedrijf = {dataType : "Integer", value : null};
    this.Betaalwijze = {dataType : "AnsiString", value : null};
    this.BetaalWijzeStornering = {dataType : "AnsiString", value : null};
    this.BICbank = {dataType : "AnsiString", value : null};
    this.BICbank2 = {dataType : "AnsiString", value : null};
    this.Body = {dataType : "WideString", value : null};
    this.Boekhoudpakket = {dataType : "AnsiString", value : null};
    this.Bondslid = {dataType : "Boolean", value : null};
    this.Bundelen = {dataType : "Boolean", value : null};
    this.Certificaat = {dataType : "AnsiString", value : null};
    this.Contactpersoon = {dataType : "AnsiString", value : null};
    this.DatumTm1 = {dataType : "DateTime", value : null};
    this.DatumTm10 = {dataType : "DateTime", value : null};
    this.DatumTm11 = {dataType : "DateTime", value : null};
    this.DatumTm12 = {dataType : "DateTime", value : null};
    this.DatumTm2 = {dataType : "DateTime", value : null};
    this.DatumTm3 = {dataType : "DateTime", value : null};
    this.DatumTm4 = {dataType : "DateTime", value : null};
    this.DatumTm5 = {dataType : "DateTime", value : null};
    this.DatumTm6 = {dataType : "DateTime", value : null};
    this.DatumTm7 = {dataType : "DateTime", value : null};
    this.DatumTm8 = {dataType : "DateTime", value : null};
    this.DatumTm9 = {dataType : "DateTime", value : null};
    this.DatumVoorraadBijgewerkt = {dataType : "DateTime", value : null};
    this.DefaultAantalTermijnen = {dataType : "AnsiString", value : null};
    this.DefaultGeslacht = {dataType : "AnsiString", value : null};
    this.DefaultSoortLid = {dataType : "AnsiString", value : null};
    this.EMail = {dataType : "AnsiString", value : null};
    this.EmailBetalingsMutaties = {dataType : "AnsiString", value : null};
    this.EmailBondsMutaties = {dataType : "AnsiString", value : null};
    this.EtikFontSize = {dataType : "Integer", value : null};
    this.Etik_Adres = {dataType : "AnsiString", value : null};
    this.Etik_Afzender = {dataType : "AnsiString", value : null};
    this.Etik_banen = {dataType : "Integer", value : null};
    this.Etik_breedte = {dataType : "Integer", value : null};
    this.Etik_hoogte = {dataType : "Integer", value : null};
    this.Etik_Land = {dataType : "AnsiString", value : null};
    this.Etik_Layout_Naam = {dataType : "AnsiString", value : null};
    this.Etik_links = {dataType : "Integer", value : null};
    this.Etik_rijen = {dataType : "Integer", value : null};
    this.Etik_top = {dataType : "Integer", value : null};
    this.ExternVerwerken = {dataType : "Boolean", value : null};
    this.Fact_Bold = {dataType : "Boolean", value : null};
    this.Fact_Doc = {dataType : "AnsiString", value : null};
    this.Fact_Font = {dataType : "AnsiString", value : null};
    this.Fact_Italic = {dataType : "Boolean", value : null};
    this.Fact_Left = {dataType : "Integer", value : null};
    this.Fact_Soort = {dataType : "AnsiString", value : null};
    this.Fact_Tekst1 = {dataType : "WideString", value : null};
    this.Fact_Tekst2 = {dataType : "WideString", value : null};
    this.Fact_Tekst3 = {dataType : "WideString", value : null};
    this.Fact_Top = {dataType : "Integer", value : null};
    this.Fax = {dataType : "AnsiString", value : null};
    this.FormaatPostcode = {dataType : "AnsiString", value : null};
    this.GetEMailAccount = {dataType : "AnsiString", value : null};
    this.GetEmailKey = {dataType : "AnsiString", value : null};
    this.GiroRekNr = {dataType : "AnsiString", value : null};
    this.GTFileName = {dataType : "AnsiString", value : null};
    this.GUIDZender = {dataType : "AnsiString", value : null};
    this.HuisNr = {dataType : "Integer", value : null};
    this.HuisNrAanv = {dataType : "AnsiString", value : null};
    this.HuisNrAanvBank = {dataType : "AnsiString", value : null};
    this.HuisNrAanvPost = {dataType : "AnsiString", value : null};
    this.HuisNrBank = {dataType : "Integer", value : null};
    this.HuisnrPost = {dataType : "Integer", value : null};
    this.IBANkey = {dataType : "AnsiString", value : null};
    this.IBANuser = {dataType : "AnsiString", value : null};
    this.IdentifierKey = {dataType : "AnsiString", value : null};
    this.IncassantId = {dataType : "AnsiString", value : null};
    this.IndVerzamelLeden = {dataType : "Boolean", value : null};
    this.IndVerzamelTussen = {dataType : "Boolean", value : null};
    this.IPadresBroker = {dataType : "AnsiString", value : null};
    this.Issuer = {dataType : "AnsiString", value : null};
    this.KIX = {dataType : "Boolean", value : null};
    this.LabelBedrag1 = {dataType : "AnsiString", value : null};
    this.LabelBedrag2 = {dataType : "AnsiString", value : null};
    this.LabelBedrag3 = {dataType : "AnsiString", value : null};
    this.LabelBedrag4 = {dataType : "AnsiString", value : null};
    this.LabelCode1 = {dataType : "AnsiString", value : null};
    this.LabelCode2 = {dataType : "AnsiString", value : null};
    this.LabelCode3 = {dataType : "AnsiString", value : null};
    this.LabelCode4 = {dataType : "AnsiString", value : null};
    this.LabelDec1 = {dataType : "AnsiString", value : null};
    this.LabelDec2 = {dataType : "AnsiString", value : null};
    this.LabelDec3 = {dataType : "AnsiString", value : null};
    this.LabelDec4 = {dataType : "AnsiString", value : null};
    this.LabelGroep = {dataType : "AnsiString", value : null};
    this.LabelGroepen = {dataType : "AnsiString", value : null};
    this.LabelNum1 = {dataType : "AnsiString", value : null};
    this.LabelNum2 = {dataType : "AnsiString", value : null};
    this.LabelNum3 = {dataType : "AnsiString", value : null};
    this.LabelNum4 = {dataType : "AnsiString", value : null};
    this.LabelVlag1 = {dataType : "AnsiString", value : null};
    this.Labelvlag10 = {dataType : "AnsiString", value : null};
    this.Labelvlag11 = {dataType : "AnsiString", value : null};
    this.Labelvlag12 = {dataType : "AnsiString", value : null};
    this.Labelvlag13 = {dataType : "AnsiString", value : null};
    this.Labelvlag14 = {dataType : "AnsiString", value : null};
    this.Labelvlag15 = {dataType : "AnsiString", value : null};
    this.Labelvlag16 = {dataType : "AnsiString", value : null};
    this.LabelVlag2 = {dataType : "AnsiString", value : null};
    this.LabelVlag3 = {dataType : "AnsiString", value : null};
    this.LabelVlag4 = {dataType : "AnsiString", value : null};
    this.LabelVlag5 = {dataType : "AnsiString", value : null};
    this.LabelVlag6 = {dataType : "AnsiString", value : null};
    this.Labelvlag7 = {dataType : "AnsiString", value : null};
    this.Labelvlag8 = {dataType : "AnsiString", value : null};
    this.Labelvlag9 = {dataType : "AnsiString", value : null};
    this.LabelVrij1 = {dataType : "AnsiString", value : null};
    this.LabelVrij2 = {dataType : "AnsiString", value : null};
    this.LabelVrij3 = {dataType : "AnsiString", value : null};
    this.LabelVrij4 = {dataType : "AnsiString", value : null};
    this.Land = {dataType : "AnsiString", value : null};
    this.LandPost = {dataType : "AnsiString", value : null};
    this.LastId = {dataType : "Integer", value : null};
    this.LidNrAutom = {dataType : "Boolean", value : null};
    this.Logo = {dataType : "AnsiString", value : null};
    this.LogoFilename = {dataType : "AnsiString", value : null};
    this.MailKey = {dataType : "AnsiString", value : null};
    this.MailUsername = {dataType : "AnsiString", value : null};
    this.MethodeInlezenStortingen = {dataType : "AnsiString", value : null};
    this.MethodeTermijnen = {dataType : "AnsiString", value : null};
    this.MethodeUitwisseling = {dataType : "AnsiString", value : null};
    this.MoederBedrijf = {dataType : "Integer", value : null};
    this.MT940FileName = {dataType : "AnsiString", value : null};
    this.Naam = {dataType : "AnsiString", value : null};
    this.NaamAccount = {dataType : "AnsiString", value : null};
    this.NaamBank = {dataType : "AnsiString", value : null};
    this.NaamBond = {dataType : "AnsiString", value : null};
    this.Naam_2 = {dataType : "AnsiString", value : null};
    this.NrBond = {dataType : "AnsiString", value : null};
    this.Opmerking = {dataType : "WideString", value : null};
    this.passPhrase = {dataType : "AnsiString", value : null};
    this.Periode = {dataType : "Integer", value : null};
    this.Plaats = {dataType : "AnsiString", value : null};
    this.PlaatsBank = {dataType : "AnsiString", value : null};
    this.PlaatsPost = {dataType : "AnsiString", value : null};
    this.Postcode = {dataType : "AnsiString", value : null};
    this.PostcodeBank = {dataType : "AnsiString", value : null};
    this.PostcodeKey = {dataType : "AnsiString", value : null};
    this.PostcodePost = {dataType : "AnsiString", value : null};
    this.ProxyPort = {dataType : "AnsiString", value : null};
    this.ProxyServer = {dataType : "AnsiString", value : null};
    this.RekeningNrBank = {dataType : "AnsiString", value : null};
    this.RekeningNrImport = {dataType : "AnsiString", value : null};
    this.RekeningNrKas = {dataType : "AnsiString", value : null};
    this.RekeningNrLeden = {dataType : "AnsiString", value : null};
    this.RekeningNrTussen = {dataType : "AnsiString", value : null};
    this.Route = {dataType : "WideString", value : null};
    this.RouteFileName = {dataType : "AnsiString", value : null};
    this.SchemaBijwerken = {dataType : "Boolean", value : null};
    this.SchemaServer = {dataType : "AnsiString", value : null};
    this.SoortPeriode = {dataType : "AnsiString", value : null};
    this.Sporttaal = {dataType : "Boolean", value : null};
    this.Straat = {dataType : "AnsiString", value : null};
    this.StraatBank = {dataType : "AnsiString", value : null};
    this.Straatpost = {dataType : "AnsiString", value : null};
    this.TabAdressen = {dataType : "Boolean", value : null};
    this.TabBankRek = {dataType : "Boolean", value : null};
    this.TabBetalingen = {dataType : "Boolean", value : null};
    this.TabBrieven = {dataType : "Boolean", value : null};
    this.TabContact = {dataType : "Boolean", value : null};
    this.TabCursussen = {dataType : "Boolean", value : null};
    this.TabDocumenten = {dataType : "Boolean", value : null};
    this.TabExtra = {dataType : "Boolean", value : null};
    this.TabFinancieel = {dataType : "Boolean", value : null};
    this.TabKenmerken = {dataType : "Boolean", value : null};
    this.TabKinderen = {dataType : "Boolean", value : null};
    this.TabMutaties = {dataType : "Boolean", value : null};
    this.TabProducten = {dataType : "Boolean", value : null};
    this.TabRelaties = {dataType : "Boolean", value : null};
    this.TabVerdiensten = {dataType : "Boolean", value : null};
    this.TabVrijeVelden = {dataType : "Boolean", value : null};
    this.TelNr = {dataType : "AnsiString", value : null};
    this.Typ = {dataType : "AnsiString", value : null};
    this.Verzekeraar = {dataType : "Integer", value : null};
    this.Vlag1 = {dataType : "Boolean", value : null};
    this.Vlag10 = {dataType : "Boolean", value : null};
    this.Vlag11 = {dataType : "Boolean", value : null};
    this.Vlag12 = {dataType : "Boolean", value : null};
    this.Vlag13 = {dataType : "Boolean", value : null};
    this.Vlag14 = {dataType : "Boolean", value : null};
    this.Vlag15 = {dataType : "Boolean", value : null};
    this.Vlag16 = {dataType : "Boolean", value : null};
    this.Vlag2 = {dataType : "Boolean", value : null};
    this.Vlag3 = {dataType : "Boolean", value : null};
    this.Vlag4 = {dataType : "Boolean", value : null};
    this.Vlag5 = {dataType : "Boolean", value : null};
    this.Vlag6 = {dataType : "Boolean", value : null};
    this.Vlag7 = {dataType : "Boolean", value : null};
    this.Vlag8 = {dataType : "Boolean", value : null};
    this.Vlag9 = {dataType : "Boolean", value : null};
    this.Website = {dataType : "AnsiString", value : null};
};
__namespace.TBedrijf.prototype = new RemObjects.SDK.ROStructType();
__namespace.TBedrijf.prototype.constructor = __namespace.TBedrijf;
RemObjects.SDK.RTTI["TBedrijf"] = __namespace.TBedrijf;


// Array: TAanhefArray
__namespace.TAanhefArray = function TAanhefArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TAanhef";
};
__namespace.TAanhefArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TAanhefArray.prototype.constructor = __namespace.TAanhefArray;
RemObjects.SDK.RTTI["TAanhefArray"] = __namespace.TAanhefArray;

// Array: TBedrijfArray
__namespace.TBedrijfArray = function TBedrijfArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TBedrijf";
};
__namespace.TBedrijfArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TBedrijfArray.prototype.constructor = __namespace.TBedrijfArray;
RemObjects.SDK.RTTI["TBedrijfArray"] = __namespace.TBedrijfArray;

// Array: TBetalingArray
__namespace.TBetalingArray = function TBetalingArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TBetaling";
};
__namespace.TBetalingArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TBetalingArray.prototype.constructor = __namespace.TBetalingArray;
RemObjects.SDK.RTTI["TBetalingArray"] = __namespace.TBetalingArray;

// Array: TCategorieArray
__namespace.TCategorieArray = function TCategorieArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TCategorie";
};
__namespace.TCategorieArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TCategorieArray.prototype.constructor = __namespace.TCategorieArray;
RemObjects.SDK.RTTI["TCategorieArray"] = __namespace.TCategorieArray;

// Array: TFunctieArray
__namespace.TFunctieArray = function TFunctieArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TFunctie";
};
__namespace.TFunctieArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TFunctieArray.prototype.constructor = __namespace.TFunctieArray;
RemObjects.SDK.RTTI["TFunctieArray"] = __namespace.TFunctieArray;

// Array: TGroepArray
__namespace.TGroepArray = function TGroepArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TGroep";
};
__namespace.TGroepArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TGroepArray.prototype.constructor = __namespace.TGroepArray;
RemObjects.SDK.RTTI["TGroepArray"] = __namespace.TGroepArray;

// Array: TGrpArray
__namespace.TGrpArray = function TGrpArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TGrp";
};
__namespace.TGrpArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TGrpArray.prototype.constructor = __namespace.TGrpArray;
RemObjects.SDK.RTTI["TGrpArray"] = __namespace.TGrpArray;

// Array: TGrpBetArray
__namespace.TGrpBetArray = function TGrpBetArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TGrpBet";
};
__namespace.TGrpBetArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TGrpBetArray.prototype.constructor = __namespace.TGrpBetArray;
RemObjects.SDK.RTTI["TGrpBetArray"] = __namespace.TGrpBetArray;

// Array: TIntegerArray
__namespace.TIntegerArray = function TIntegerArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "Integer";
};
__namespace.TIntegerArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TIntegerArray.prototype.constructor = __namespace.TIntegerArray;
RemObjects.SDK.RTTI["TIntegerArray"] = __namespace.TIntegerArray;

// Array: TKenmerkArray
__namespace.TKenmerkArray = function TKenmerkArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TKenmerk";
};
__namespace.TKenmerkArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TKenmerkArray.prototype.constructor = __namespace.TKenmerkArray;
RemObjects.SDK.RTTI["TKenmerkArray"] = __namespace.TKenmerkArray;

// Array: TKenmKodeArray
__namespace.TKenmKodeArray = function TKenmKodeArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TKenmKode";
};
__namespace.TKenmKodeArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TKenmKodeArray.prototype.constructor = __namespace.TKenmKodeArray;
RemObjects.SDK.RTTI["TKenmKodeArray"] = __namespace.TKenmKodeArray;

// Array: TMutRedenArray
__namespace.TMutRedenArray = function TMutRedenArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TMutReden";
};
__namespace.TMutRedenArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TMutRedenArray.prototype.constructor = __namespace.TMutRedenArray;
RemObjects.SDK.RTTI["TMutRedenArray"] = __namespace.TMutRedenArray;

// Array: TPersBetArray
__namespace.TPersBetArray = function TPersBetArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TPersBet";
};
__namespace.TPersBetArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TPersBetArray.prototype.constructor = __namespace.TPersBetArray;
RemObjects.SDK.RTTI["TPersBetArray"] = __namespace.TPersBetArray;

// Array: TPersoonArray
__namespace.TPersoonArray = function TPersoonArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TPersoon";
};
__namespace.TPersoonArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TPersoonArray.prototype.constructor = __namespace.TPersoonArray;
RemObjects.SDK.RTTI["TPersoonArray"] = __namespace.TPersoonArray;

// Array: TPersPeriArray
__namespace.TPersPeriArray = function TPersPeriArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TPersPeri";
};
__namespace.TPersPeriArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TPersPeriArray.prototype.constructor = __namespace.TPersPeriArray;
RemObjects.SDK.RTTI["TPersPeriArray"] = __namespace.TPersPeriArray;

// Array: TRegioArray
__namespace.TRegioArray = function TRegioArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TRegio";
};
__namespace.TRegioArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TRegioArray.prototype.constructor = __namespace.TRegioArray;
RemObjects.SDK.RTTI["TRegioArray"] = __namespace.TRegioArray;

// Array: TSoortBetalingArray
__namespace.TSoortBetalingArray = function TSoortBetalingArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TSoortBetaling";
};
__namespace.TSoortBetalingArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TSoortBetalingArray.prototype.constructor = __namespace.TSoortBetalingArray;
RemObjects.SDK.RTTI["TSoortBetalingArray"] = __namespace.TSoortBetalingArray;

// Array: TSoortLidArray
__namespace.TSoortLidArray = function TSoortLidArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TSoortLid";
};
__namespace.TSoortLidArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TSoortLidArray.prototype.constructor = __namespace.TSoortLidArray;
RemObjects.SDK.RTTI["TSoortLidArray"] = __namespace.TSoortLidArray;

// Array: TStringArray
__namespace.TStringArray = function TStringArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "AnsiString";
};
__namespace.TStringArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TStringArray.prototype.constructor = __namespace.TStringArray;
RemObjects.SDK.RTTI["TStringArray"] = __namespace.TStringArray;

// Array: TTitelArray
__namespace.TTitelArray = function TTitelArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TTitel";
};
__namespace.TTitelArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TTitelArray.prototype.constructor = __namespace.TTitelArray;
RemObjects.SDK.RTTI["TTitelArray"] = __namespace.TTitelArray;

// Array: TUserArray
__namespace.TUserArray = function TUserArray() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "TUser";
};
__namespace.TUserArray.prototype = new RemObjects.SDK.ROArrayType();
__namespace.TUserArray.prototype.constructor = __namespace.TUserArray;
RemObjects.SDK.RTTI["TUserArray"] = __namespace.TUserArray;


// Exception: ETestException
__namespace.ETestException = function ETestException(e) {
    RemObjects.SDK.ROException.call(this, e);
    this.fields.ErrorCode  = {dataType : "Integer", value : null};
    this.fields.AdditionalInfo  = {dataType : "AnsiString", value : null};
};
__namespace.ETestException.prototype = new RemObjects.SDK.ROException();
RemObjects.SDK.RTTI["ETestException"] = __namespace.ETestException;



// Service: PolderJSONService
__namespace.PolderJSONService = function PolderJSONService(__channel, __message, __service_name) {
  RemObjects.SDK.ROService.call(this, __channel, __message, __service_name);
  this.fServiceName = this.fServiceName || __service_name || "PolderJSONService";
};


__namespace.PolderJSONService.prototype.SvcUser = function(
	Actie,
	UserIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcUser");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("UserIn", "TUser", UserIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __UserOut = __message.read("UserOut", "TUserArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
		__success(
		__UserOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcSoortLid = function(
	Actie,
	Username,
	SoortLidIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcSoortLid");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("SoortLidIn", "TSoortLid", SoortLidIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __SoortLidOut = __message.read("SoortLidOut", "TSoortLidArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__SoortLidOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcPersoon = function(
	Actie,
	Username,
	PersoonIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcPersoon");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("PersoonIn", "TPersoon", PersoonIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __PersoonOut = __message.read("PersoonOut", "TPersoonArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__PersoonOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcRegio = function(
	Actie,
	Username,
	RegioIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcRegio");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("RegioIn", "TRegio", RegioIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __RegioOut = __message.read("RegioOut", "TRegioArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__RegioOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcGrp = function(
	Actie,
	Username,
	GrpIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcGrp");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("GrpIn", "TGrp", GrpIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __GrpOut = __message.read("GrpOut", "TGrpArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__GrpOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcFunctie = function(
	Actie,
	Username,
	FunctieIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcFunctie");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("FunctieIn", "TFunctie", FunctieIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __FunctieOut = __message.read("FunctieOut", "TFunctieArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__FunctieOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcSoortBetaling = function(
	Actie,
	Username,
	SoortBetalingIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcSoortBetaling");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("SoortBetalingIn", "TSoortBetaling", SoortBetalingIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __SoortBetalingOut = __message.read("SoortBetalingOut", "TSoortBetalingArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__SoortBetalingOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcMutReden = function(
	Actie,
	Username,
	MutRedenIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcMutReden");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("MutRedenIn", "TMutReden", MutRedenIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __MutRedenOut = __message.read("MutRedenOut", "TMutRedenArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__MutRedenOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcGroep = function(
	Actie,
	Username,
	GroepIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcGroep");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("GroepIn", "TGroep", GroepIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __GroepOut = __message.read("GroepOut", "TGroepArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__GroepOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcGrpBet = function(
	Actie,
	Username,
	GrpBetIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcGrpBet");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("GrpBetIn", "TGrpBet", GrpBetIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __GrpBetOut = __message.read("GrpBetOut", "TGrpBetArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__GrpBetOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcAanhef = function(
	Actie,
	Username,
	AanhefIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcAanhef");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("AanhefIn", "TAanhef", AanhefIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __AanhefOut = __message.read("AanhefOut", "TAanhefArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__AanhefOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcTitel = function(
	Actie,
	Username,
	TitelIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcTitel");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("TitelIn", "TTitel", TitelIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __TitelOut = __message.read("TitelOut", "TTitelArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__TitelOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcCategorie = function(
	Actie,
	Username,
	CategorieIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcCategorie");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("CategorieIn", "TCategorie", CategorieIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __CategorieOut = __message.read("CategorieOut", "TCategorieArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__CategorieOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcKenmerk = function(
	Actie,
	Username,
	KenmerkIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcKenmerk");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("KenmerkIn", "TKenmerk", KenmerkIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __KenmerkOut = __message.read("KenmerkOut", "TKenmerkArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__KenmerkOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcKenmKode = function(
	Actie,
	Username,
	KenmKodeIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcKenmKode");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("KenmKodeIn", "TKenmKode", KenmKodeIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __KenmKodeOut = __message.read("KenmKodeOut", "TKenmKodeArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__KenmKodeOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcPersPeri = function(
	Actie,
	Username,
	PersPeriIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcPersPeri");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("PersPeriIn", "TPersPeri", PersPeriIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __PersPeriOut = __message.read("PersPeriOut", "TPersPeriArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__PersPeriOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcPersBet = function(
	Actie,
	Username,
	PersBetIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcPersBet");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("PersBetIn", "TPersBet", PersBetIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __PersBetOut = __message.read("PersBetOut", "TPersBetArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__PersBetOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcBetaling = function(
	Actie,
	Username,
	BetalingIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcBetaling");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("BetalingIn", "TBetaling", BetalingIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __BetalingOut = __message.read("BetalingOut", "TBetalingArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__BetalingOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SvcBedrijf = function(
	Actie,
	Username,
	BedrijfIn,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SvcBedrijf");
        msg.write("Actie", "AnsiString", Actie);
        msg.write("Username", "AnsiString", Username);
        msg.write("BedrijfIn", "TBedrijf", BedrijfIn);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __BedrijfOut = __message.read("BedrijfOut", "TBedrijfArray");
		var __Rslt = __message.read("Rslt", "Boolean");
		var __Mess = __message.read("Mess", "AnsiString");
        if (__Mess != '') {
          alert(JSON.stringify(__Mess));
        }
        __success(
		__BedrijfOut,
		__Rslt,
		__Mess
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.Sum = function(
	A,
	B,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "Sum");
        msg.write("A", "Integer", A);
        msg.write("B", "Integer", B);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "Integer");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.GetServerTime = function(
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "GetServerTime");
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "DateTime");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.TestIntegerArray = function(
	anArray,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "TestIntegerArray");
        msg.write("anArray", "TIntegerArray", anArray);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "TIntegerArray");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.TestStringArray = function(
	anArray,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "TestStringArray");
        msg.write("anArray", "TStringArray", anArray);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "TStringArray");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.EchoBinary = function(
	BinIN,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "EchoBinary");
        msg.write("BinIN", "Binary", BinIN);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __BinOUT = __message.read("BinOUT", "Binary");
	        __success(
		__BinOUT
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.SomeTypes = function(
	aString,
	aWidestring,
	anInteger,
	aCurrency,
	aDatetime,
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "SomeTypes");
        msg.write("aString", "AnsiString", aString);
        msg.write("aWidestring", "WideString", aWidestring);
        msg.write("anInteger", "Integer", anInteger);
        msg.write("aCurrency", "Currency", aCurrency);
        msg.write("aDatetime", "DateTime", aDatetime);
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __aString = __message.read("aString", "AnsiString");
		var __aWidestring = __message.read("aWidestring", "WideString");
		var __anInteger = __message.read("anInteger", "Integer");
		var __aCurrency = __message.read("aCurrency", "Currency");
		var __aDatetime = __message.read("aDatetime", "DateTime");
	        __success(
		__aString,
		__aWidestring,
		__anInteger,
		__aCurrency,
		__aDatetime
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.CustomObjectAsString = function(
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "CustomObjectAsString");
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "AnsiString");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.CustomObjectAsStream = function(
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "CustomObjectAsStream");
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
		var __result = __message.read("Result", "Binary");
	        __success(
		__result
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.RaiseError = function(
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "RaiseError");
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
	        __success(
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

__namespace.PolderJSONService.prototype.RaiseTestException = function(
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "RaiseTestException");
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
	        __success(
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};



